[book]
authors = ["Bishounen"]
language = "en"
multilingual = false
src = "src"
title = "Knowledge Base"

[output.html.fold]
enable = true
level = 0

[preprocessor.customization]
command = "python customization.py"
customization = "nx"